/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPrivateRouteImport } from './routes/_app._private'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppCercaRouteImport } from './routes/_app.cerca'
import { Route as AppCreditsRouteImport } from './routes/_app.credits'
import { Route as AppPrivacyRouteImport } from './routes/_app.privacy'
import { Route as AppTermsRouteImport } from './routes/_app.terms'
import { Route as GuestLoginRouteImport } from './routes/_guest.login'
import { Route as GuestRegisterRouteImport } from './routes/_guest.register'
import { Route as AppPrivateBacklogRouteImport } from './routes/_app._private.backlog'
import { Route as AppAccountIndexRouteImport } from './routes/_app.account.index'
import { Route as AppAccountDaSistemareRouteImport } from './routes/_app.account.da-sistemare'
import { Route as AppAccountLibrerieRouteImport } from './routes/_app.account.librerie'
import { Route as AppAccountNascostiRouteImport } from './routes/_app.account.nascosti'
import { Route as AppAccountProfiloRouteImport } from './routes/_app.account.profilo'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAdminMancantiRouteImport } from './routes/_app.admin.mancanti'
import { Route as AppAdminScartiRouteImport } from './routes/_app.admin.scarti'
import { Route as AppAdminSegnalatiRouteImport } from './routes/_app.admin.segnalati'
import { Route as AppAdminUtentiRouteImport } from './routes/_app.admin.utenti'
import { Route as AppCondivisaTokenRouteImport } from './routes/_app.condivisa.$token'
import { Route as AppGamesSlugRouteImport } from './routes/_app.games.$slug'
import { Route as AppPrivatePlaylistIndexRouteImport } from './routes/_app._private.playlist.index'
import { Route as AppPrivatePlaylistIdRouteImport } from './routes/_app._private.playlist.$id'
import { Route as AppAdminGiochiSlugRouteImport } from './routes/_app.admin.giochi.$slug'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivateRoute = AppPrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCercaRoute = AppCercaRouteImport.update({
  id: '/cerca',
  path: '/cerca',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditsRoute = AppCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)
const AppPrivateBacklogRoute = AppPrivateBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => AppPrivateRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountDaSistemareRoute = AppAccountDaSistemareRouteImport.update({
  id: '/da-sistemare',
  path: '/da-sistemare',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountLibrerieRoute = AppAccountLibrerieRouteImport.update({
  id: '/librerie',
  path: '/librerie',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountNascostiRoute = AppAccountNascostiRouteImport.update({
  id: '/nascosti',
  path: '/nascosti',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountProfiloRoute = AppAccountProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMancantiRoute = AppAdminMancantiRouteImport.update({
  id: '/mancanti',
  path: '/mancanti',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminScartiRoute = AppAdminScartiRouteImport.update({
  id: '/scarti',
  path: '/scarti',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSegnalatiRoute = AppAdminSegnalatiRouteImport.update({
  id: '/segnalati',
  path: '/segnalati',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUtentiRoute = AppAdminUtentiRouteImport.update({
  id: '/utenti',
  path: '/utenti',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppCondivisaTokenRoute = AppCondivisaTokenRouteImport.update({
  id: '/condivisa/$token',
  path: '/condivisa/$token',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesSlugRoute = AppGamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivatePlaylistIndexRoute = AppPrivatePlaylistIndexRouteImport.update({
  id: '/playlist/',
  path: '/playlist/',
  getParentRoute: () => AppPrivateRoute,
} as any)
const AppPrivatePlaylistIdRoute = AppPrivatePlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => AppPrivateRoute,
} as any)
const AppAdminGiochiSlugRoute = AppAdminGiochiSlugRouteImport.update({
  id: '/giochi/$slug',
  path: '/giochi/$slug',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/account': typeof AppAccountRouteWithChildren
  '/admin': typeof AppAdminRouteWithChildren
  '/cerca': typeof AppCercaRoute
  '/credits': typeof AppCreditsRoute
  '/privacy': typeof AppPrivacyRoute
  '/terms': typeof AppTermsRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/backlog': typeof AppPrivateBacklogRoute
  '/account/da-sistemare': typeof AppAccountDaSistemareRoute
  '/account/librerie': typeof AppAccountLibrerieRoute
  '/account/nascosti': typeof AppAccountNascostiRoute
  '/account/profilo': typeof AppAccountProfiloRoute
  '/admin/mancanti': typeof AppAdminMancantiRoute
  '/admin/scarti': typeof AppAdminScartiRoute
  '/admin/segnalati': typeof AppAdminSegnalatiRoute
  '/admin/utenti': typeof AppAdminUtentiRoute
  '/condivisa/$token': typeof AppCondivisaTokenRoute
  '/games/$slug': typeof AppGamesSlugRoute
  '/account/': typeof AppAccountIndexRoute
  '/admin/': typeof AppAdminIndexRoute
  '/playlist/$id': typeof AppPrivatePlaylistIdRoute
  '/admin/giochi/$slug': typeof AppAdminGiochiSlugRoute
  '/playlist/': typeof AppPrivatePlaylistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/cerca': typeof AppCercaRoute
  '/credits': typeof AppCreditsRoute
  '/privacy': typeof AppPrivacyRoute
  '/terms': typeof AppTermsRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/backlog': typeof AppPrivateBacklogRoute
  '/account/da-sistemare': typeof AppAccountDaSistemareRoute
  '/account/librerie': typeof AppAccountLibrerieRoute
  '/account/nascosti': typeof AppAccountNascostiRoute
  '/account/profilo': typeof AppAccountProfiloRoute
  '/admin/mancanti': typeof AppAdminMancantiRoute
  '/admin/scarti': typeof AppAdminScartiRoute
  '/admin/segnalati': typeof AppAdminSegnalatiRoute
  '/admin/utenti': typeof AppAdminUtentiRoute
  '/condivisa/$token': typeof AppCondivisaTokenRoute
  '/games/$slug': typeof AppGamesSlugRoute
  '/account': typeof AppAccountIndexRoute
  '/admin': typeof AppAdminIndexRoute
  '/playlist/$id': typeof AppPrivatePlaylistIdRoute
  '/admin/giochi/$slug': typeof AppAdminGiochiSlugRoute
  '/playlist': typeof AppPrivatePlaylistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_app/_private': typeof AppPrivateRouteWithChildren
  '/_app/account': typeof AppAccountRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/cerca': typeof AppCercaRoute
  '/_app/credits': typeof AppCreditsRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/terms': typeof AppTermsRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_private/backlog': typeof AppPrivateBacklogRoute
  '/_app/account/da-sistemare': typeof AppAccountDaSistemareRoute
  '/_app/account/librerie': typeof AppAccountLibrerieRoute
  '/_app/account/nascosti': typeof AppAccountNascostiRoute
  '/_app/account/profilo': typeof AppAccountProfiloRoute
  '/_app/admin/mancanti': typeof AppAdminMancantiRoute
  '/_app/admin/scarti': typeof AppAdminScartiRoute
  '/_app/admin/segnalati': typeof AppAdminSegnalatiRoute
  '/_app/admin/utenti': typeof AppAdminUtentiRoute
  '/_app/condivisa/$token': typeof AppCondivisaTokenRoute
  '/_app/games/$slug': typeof AppGamesSlugRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/_private/playlist/$id': typeof AppPrivatePlaylistIdRoute
  '/_app/admin/giochi/$slug': typeof AppAdminGiochiSlugRoute
  '/_app/_private/playlist/': typeof AppPrivatePlaylistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cerca'
    | '/credits'
    | '/privacy'
    | '/terms'
    | '/login'
    | '/register'
    | '/backlog'
    | '/account/da-sistemare'
    | '/account/librerie'
    | '/account/nascosti'
    | '/account/profilo'
    | '/admin/mancanti'
    | '/admin/scarti'
    | '/admin/segnalati'
    | '/admin/utenti'
    | '/condivisa/$token'
    | '/games/$slug'
    | '/account/'
    | '/admin/'
    | '/playlist/$id'
    | '/admin/giochi/$slug'
    | '/playlist/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cerca'
    | '/credits'
    | '/privacy'
    | '/terms'
    | '/login'
    | '/register'
    | '/backlog'
    | '/account/da-sistemare'
    | '/account/librerie'
    | '/account/nascosti'
    | '/account/profilo'
    | '/admin/mancanti'
    | '/admin/scarti'
    | '/admin/segnalati'
    | '/admin/utenti'
    | '/condivisa/$token'
    | '/games/$slug'
    | '/account'
    | '/admin'
    | '/playlist/$id'
    | '/admin/giochi/$slug'
    | '/playlist'
  id:
    | '__root__'
    | '/_app'
    | '/_guest'
    | '/_app/_private'
    | '/_app/account'
    | '/_app/admin'
    | '/_app/cerca'
    | '/_app/credits'
    | '/_app/privacy'
    | '/_app/terms'
    | '/_guest/login'
    | '/_guest/register'
    | '/_app/'
    | '/_app/_private/backlog'
    | '/_app/account/da-sistemare'
    | '/_app/account/librerie'
    | '/_app/account/nascosti'
    | '/_app/account/profilo'
    | '/_app/admin/mancanti'
    | '/_app/admin/scarti'
    | '/_app/admin/segnalati'
    | '/_app/admin/utenti'
    | '/_app/condivisa/$token'
    | '/_app/games/$slug'
    | '/_app/account/'
    | '/_app/admin/'
    | '/_app/_private/playlist/$id'
    | '/_app/admin/giochi/$slug'
    | '/_app/_private/playlist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_private': {
      id: '/_app/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppPrivateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cerca': {
      id: '/_app/cerca'
      path: '/cerca'
      fullPath: '/cerca'
      preLoaderRoute: typeof AppCercaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credits': {
      id: '/_app/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AppCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_app/_private/backlog': {
      id: '/_app/_private/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof AppPrivateBacklogRouteImport
      parentRoute: typeof AppPrivateRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/da-sistemare': {
      id: '/_app/account/da-sistemare'
      path: '/da-sistemare'
      fullPath: '/account/da-sistemare'
      preLoaderRoute: typeof AppAccountDaSistemareRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/librerie': {
      id: '/_app/account/librerie'
      path: '/librerie'
      fullPath: '/account/librerie'
      preLoaderRoute: typeof AppAccountLibrerieRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/nascosti': {
      id: '/_app/account/nascosti'
      path: '/nascosti'
      fullPath: '/account/nascosti'
      preLoaderRoute: typeof AppAccountNascostiRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/profilo': {
      id: '/_app/account/profilo'
      path: '/profilo'
      fullPath: '/account/profilo'
      preLoaderRoute: typeof AppAccountProfiloRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/mancanti': {
      id: '/_app/admin/mancanti'
      path: '/mancanti'
      fullPath: '/admin/mancanti'
      preLoaderRoute: typeof AppAdminMancantiRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/scarti': {
      id: '/_app/admin/scarti'
      path: '/scarti'
      fullPath: '/admin/scarti'
      preLoaderRoute: typeof AppAdminScartiRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/segnalati': {
      id: '/_app/admin/segnalati'
      path: '/segnalati'
      fullPath: '/admin/segnalati'
      preLoaderRoute: typeof AppAdminSegnalatiRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/utenti': {
      id: '/_app/admin/utenti'
      path: '/utenti'
      fullPath: '/admin/utenti'
      preLoaderRoute: typeof AppAdminUtentiRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/condivisa/$token': {
      id: '/_app/condivisa/$token'
      path: '/condivisa/$token'
      fullPath: '/condivisa/$token'
      preLoaderRoute: typeof AppCondivisaTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/$slug': {
      id: '/_app/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof AppGamesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_private/playlist/': {
      id: '/_app/_private/playlist/'
      path: '/playlist'
      fullPath: '/playlist/'
      preLoaderRoute: typeof AppPrivatePlaylistIndexRouteImport
      parentRoute: typeof AppPrivateRoute
    }
    '/_app/_private/playlist/$id': {
      id: '/_app/_private/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof AppPrivatePlaylistIdRouteImport
      parentRoute: typeof AppPrivateRoute
    }
    '/_app/admin/giochi/$slug': {
      id: '/_app/admin/giochi/$slug'
      path: '/giochi/$slug'
      fullPath: '/admin/giochi/$slug'
      preLoaderRoute: typeof AppAdminGiochiSlugRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppPrivateRouteChildren {
  AppPrivateBacklogRoute: typeof AppPrivateBacklogRoute
  AppPrivatePlaylistIdRoute: typeof AppPrivatePlaylistIdRoute
  AppPrivatePlaylistIndexRoute: typeof AppPrivatePlaylistIndexRoute
}

const AppPrivateRouteChildren: AppPrivateRouteChildren = {
  AppPrivateBacklogRoute: AppPrivateBacklogRoute,
  AppPrivatePlaylistIdRoute: AppPrivatePlaylistIdRoute,
  AppPrivatePlaylistIndexRoute: AppPrivatePlaylistIndexRoute,
}

const AppPrivateRouteWithChildren = AppPrivateRoute._addFileChildren(
  AppPrivateRouteChildren,
)

interface AppAccountRouteChildren {
  AppAccountDaSistemareRoute: typeof AppAccountDaSistemareRoute
  AppAccountLibrerieRoute: typeof AppAccountLibrerieRoute
  AppAccountNascostiRoute: typeof AppAccountNascostiRoute
  AppAccountProfiloRoute: typeof AppAccountProfiloRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountDaSistemareRoute: AppAccountDaSistemareRoute,
  AppAccountLibrerieRoute: AppAccountLibrerieRoute,
  AppAccountNascostiRoute: AppAccountNascostiRoute,
  AppAccountProfiloRoute: AppAccountProfiloRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminMancantiRoute: typeof AppAdminMancantiRoute
  AppAdminScartiRoute: typeof AppAdminScartiRoute
  AppAdminSegnalatiRoute: typeof AppAdminSegnalatiRoute
  AppAdminUtentiRoute: typeof AppAdminUtentiRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminGiochiSlugRoute: typeof AppAdminGiochiSlugRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminMancantiRoute: AppAdminMancantiRoute,
  AppAdminScartiRoute: AppAdminScartiRoute,
  AppAdminSegnalatiRoute: AppAdminSegnalatiRoute,
  AppAdminUtentiRoute: AppAdminUtentiRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminGiochiSlugRoute: AppAdminGiochiSlugRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppPrivateRoute: typeof AppPrivateRouteWithChildren
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCercaRoute: typeof AppCercaRoute
  AppCreditsRoute: typeof AppCreditsRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppTermsRoute: typeof AppTermsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCondivisaTokenRoute: typeof AppCondivisaTokenRoute
  AppGamesSlugRoute: typeof AppGamesSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPrivateRoute: AppPrivateRouteWithChildren,
  AppAccountRoute: AppAccountRouteWithChildren,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCercaRoute: AppCercaRoute,
  AppCreditsRoute: AppCreditsRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppTermsRoute: AppTermsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCondivisaTokenRoute: AppCondivisaTokenRoute,
  AppGamesSlugRoute: AppGamesSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
