/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPrivateRouteImport } from './routes/_app._private'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppCreditsRouteImport } from './routes/_app.credits'
import { Route as AppPrivacyRouteImport } from './routes/_app.privacy'
import { Route as AppTermsRouteImport } from './routes/_app.terms'
import { Route as GuestLoginRouteImport } from './routes/_guest.login'
import { Route as GuestRegisterRouteImport } from './routes/_guest.register'
import { Route as AppPrivateBacklogRouteImport } from './routes/_app._private.backlog'
import { Route as AppGamesIdRouteImport } from './routes/_app.games.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivateRoute = AppPrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditsRoute = AppCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)
const AppPrivateBacklogRoute = AppPrivateBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => AppPrivateRoute,
} as any)
const AppGamesIdRoute = AppGamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/account': typeof AppAccountRoute
  '/credits': typeof AppCreditsRoute
  '/privacy': typeof AppPrivacyRoute
  '/terms': typeof AppTermsRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/backlog': typeof AppPrivateBacklogRoute
  '/games/$id': typeof AppGamesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/account': typeof AppAccountRoute
  '/credits': typeof AppCreditsRoute
  '/privacy': typeof AppPrivacyRoute
  '/terms': typeof AppTermsRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/backlog': typeof AppPrivateBacklogRoute
  '/games/$id': typeof AppGamesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_app/_private': typeof AppPrivateRouteWithChildren
  '/_app/account': typeof AppAccountRoute
  '/_app/credits': typeof AppCreditsRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/terms': typeof AppTermsRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_private/backlog': typeof AppPrivateBacklogRoute
  '/_app/games/$id': typeof AppGamesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/credits'
    | '/privacy'
    | '/terms'
    | '/login'
    | '/register'
    | '/backlog'
    | '/games/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/credits'
    | '/privacy'
    | '/terms'
    | '/login'
    | '/register'
    | '/backlog'
    | '/games/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_guest'
    | '/_app/_private'
    | '/_app/account'
    | '/_app/credits'
    | '/_app/privacy'
    | '/_app/terms'
    | '/_guest/login'
    | '/_guest/register'
    | '/_app/'
    | '/_app/_private/backlog'
    | '/_app/games/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_private': {
      id: '/_app/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppPrivateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credits': {
      id: '/_app/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AppCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_app/_private/backlog': {
      id: '/_app/_private/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof AppPrivateBacklogRouteImport
      parentRoute: typeof AppPrivateRoute
    }
    '/_app/games/$id': {
      id: '/_app/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof AppGamesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppPrivateRouteChildren {
  AppPrivateBacklogRoute: typeof AppPrivateBacklogRoute
}

const AppPrivateRouteChildren: AppPrivateRouteChildren = {
  AppPrivateBacklogRoute: AppPrivateBacklogRoute,
}

const AppPrivateRouteWithChildren = AppPrivateRoute._addFileChildren(
  AppPrivateRouteChildren,
)

interface AppRouteChildren {
  AppPrivateRoute: typeof AppPrivateRouteWithChildren
  AppAccountRoute: typeof AppAccountRoute
  AppCreditsRoute: typeof AppCreditsRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppTermsRoute: typeof AppTermsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGamesIdRoute: typeof AppGamesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPrivateRoute: AppPrivateRouteWithChildren,
  AppAccountRoute: AppAccountRoute,
  AppCreditsRoute: AppCreditsRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppTermsRoute: AppTermsRoute,
  AppIndexRoute: AppIndexRoute,
  AppGamesIdRoute: AppGamesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
