-- Seed della tabella di riferimento delle piattaforme.
-- Fonte: Playnite, source/Playnite/Emulation/Platforms.yaml (96 voci).
-- vectrex va senza igdb_id: Playnite le assegna il 67, gia usato da
-- mattel_intellivision. Si corregge allo step 3 col dato IGDB vero.
INSERT INTO "platforms" ("slug", "name", "igdb_id") VALUES
  ('3do', '3DO Interactive Multiplayer', 50),
  ('adobe_flash', 'Adobe Flash', NULL),
  ('amstrad_cpc', 'Amstrad CPC', 25),
  ('apple_2', 'Apple II', 75),
  ('arcade', 'Arcade', 52),
  ('arduboy', 'Arduboy', NULL),
  ('atari_2600', 'Atari 2600', 59),
  ('atari_5200', 'Atari 5200', 66),
  ('atari_7800', 'Atari 7800', 60),
  ('atari_8bit', 'Atari 8-bit', 65),
  ('atari_falcon030', 'Atari Falcon030', NULL),
  ('atari_jaguar', 'Atari Jaguar', 62),
  ('atari_lynx', 'Atari Lynx', 61),
  ('atari_st', 'Atari ST/STE', 63),
  ('bandai_wonderswan_color', 'Bandai WonderSwan Color', 123),
  ('bandai_wonderswan', 'Bandai WonderSwan', 57),
  ('coleco_vision', 'Coleco ColecoVision', 68),
  ('commodore_64', 'Commodore 64', 15),
  ('commodore_amiga_cd32', 'Commodore Amiga CD32', 114),
  ('commodore_amiga', 'Commodore Amiga', 16),
  ('commodore_cbm5x0', 'Commodore CBM-5x0', NULL),
  ('commodore_cbm2', 'Commodore CBM-II', NULL),
  ('commodore_pet', 'Commodore PET', 90),
  ('commodore_plus4', 'Commodore Plus/4', 94),
  ('commodore_vci20', 'Commodore VIC20', 71),
  ('fairchild_channelf', 'Fairchild Channel F', NULL),
  ('vectrex', 'GCE Vectrex', NULL),
  ('macintosh', 'Macintosh', 14),
  ('magnavox_odyssey_2', 'Magnavox Odyssey 2', 133),
  ('mattel_intellivision', 'Mattel Intellivision', 67),
  ('megaduck', 'Mega Duck', NULL),
  ('microsoft_msx', 'Microsoft MSX', 27),
  ('microsoft_msx2', 'Microsoft MSX2', 53),
  ('xbox360', 'Microsoft Xbox 360', 12),
  ('xbox_one', 'Microsoft Xbox One', 49),
  ('xbox_series', 'Microsoft Xbox Series', 169),
  ('xbox', 'Microsoft Xbox', 11),
  ('nec_pc88', 'NEC PC-88', NULL),
  ('nec_pc98', 'NEC PC-98', 149),
  ('nec_pcfx', 'NEC PC-FX', 274),
  ('nec_supergrafx', 'NEC SuperGrafx', 128),
  ('nec_turbografx_16', 'NEC TurboGrafx 16', 86),
  ('nec_turbografx_cd', 'NEC TurboGrafx-CD', 150),
  ('nintendo_3ds', 'Nintendo 3DS', 37),
  ('nintendo_64', 'Nintendo 64', 4),
  ('nintendo_ds', 'Nintendo DS', 20),
  ('nintendo_dsi', 'Nintendo DSi', 159),
  ('nintendo_nes', 'Nintendo Entertainment System', 18),
  ('nintendo_famicom_disk', 'Nintendo Family Computer Disk System', 51),
  ('nintendo_gameandwatch', 'Nintendo Game & Watch', NULL),
  ('nintendo_gameboyadvance', 'Nintendo Game Boy Advance', 24),
  ('nintendo_gameboycolor', 'Nintendo Game Boy Color', 22),
  ('nintendo_gameboy', 'Nintendo Game Boy', 33),
  ('nintendo_gamecube', 'Nintendo GameCube', 21),
  ('nintendo_super_nes', 'Nintendo SNES', 19),
  ('nintendo_switch', 'Nintendo Switch', 130),
  ('nintendo_switch2', 'Nintendo Switch 2', 508),
  ('nintendo_virtualboy', 'Nintendo Virtual Boy', 87),
  ('nintendo_wiiu', 'Nintendo Wii U', 41),
  ('nintendo_wii', 'Nintendo Wii', 5),
  ('pc_dos', 'PC (DOS)', 13),
  ('pc_linux', 'PC (Linux)', 3),
  ('pc_windows', 'PC (Windows)', 6),
  ('sega_32x', 'Sega 32X', 30),
  ('sega_cd', 'Sega CD', 78),
  ('sega_dreamcast', 'Sega Dreamcast', 23),
  ('sega_gamegear', 'Sega Game Gear', 35),
  ('sega_genesis', 'Sega Genesis', 29),
  ('sega_mastersystem', 'Sega Master System', 64),
  ('sega_saturn', 'Sega Saturn', 32),
  ('sega_sg1000', 'Sega SG-1000', 84),
  ('sharp_x1', 'Sharp X1', NULL),
  ('sharp_x68000', 'Sharp X68000', 121),
  ('sinclair_zxspectrum3', 'Sinclair ZX Spectrum +3', NULL),
  ('sinclair_zxspectrum', 'Sinclair ZX Spectrum', 26),
  ('sinclair_zx81', 'Sinclair ZX81', 373),
  ('snk_neogeo_aes', 'SNK Neo Geo AES', 80),
  ('snk_neogeo_cd', 'SNK Neo Geo CD', 136),
  ('snk_neogeopocket_color', 'SNK Neo Geo Pocket Color', 120),
  ('snk_neogeopocket', 'SNK Neo Geo Pocket', 119),
  ('sony_playstation2', 'Sony PlayStation 2', 8),
  ('sony_playstation3', 'Sony PlayStation 3', 9),
  ('sony_playstation4', 'Sony PlayStation 4', 48),
  ('sony_playstation5', 'Sony PlayStation 5', 167),
  ('sony_psp', 'Sony PlayStation Portable', 38),
  ('sony_vita', 'Sony PlayStation Vita', 46),
  ('sony_playstation', 'Sony PlayStation', 7),
  ('ti_83', 'Texas Instruments TI-83', NULL),
  ('thomson_mo5', 'Thomson MO5', 156),
  ('thomson_to7', 'Thomson TO7', NULL),
  ('tic_80', 'TIC-80', NULL),
  ('uzebox', 'Uzebox', NULL),
  ('wasm4', 'WASM-4', NULL),
  ('watara_supervision', 'Watara Supervision', NULL),
  ('philips_cdi', 'Philips CD-i', 117),
  ('pokemon_mini', 'Pokémon mini', 166)
ON CONFLICT ("slug") DO NOTHING;
